name: e_commerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core packages
  intl: any
  equatable: ^2.0.7
  dartz: ^0.10.1

  # UI
  cached_network_image: ^3.4.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  flutter_otp_text_field: ^1.5.1+1
  persistent_bottom_nav_bar: ^6.2.1
  dots_indicator: ^4.0.1

  # Routing
  go_router: ^14.8.1

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Utilities
  device_preview: ^1.2.0
  flutter_launcher_icons: ^0.14.4
  rename_app: ^1.6.3

dev_dependencies:
  # Flutter SDK
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^5.0.0
  riverpod_lint: ^2.6.1

  # Code generation
  build_runner: ^2.4.9
  riverpod_generator: ^2.6.1

  # Analyzer (manual pins to avoid conflicts)
  analyzer: 6.11.0
  analyzer_plugin: 0.11.3

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Black.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo/Cairo-ExtraBold.ttf
        - asset: assets/fonts/Cairo/Cairo-ExtraLight.ttf
        - asset: assets/fonts/Cairo/Cairo-Light.ttf
        - asset: assets/fonts/Cairo/Cairo-Medium.ttf
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-SemiBold.ttf

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto/Roboto-ExtraBold.ttf
        - asset: assets/fonts/Roboto/Roboto-ExtraLight.ttf
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-SemiBold.ttf

  assets:
    - assets/fonts/Cairo/
    - assets/fonts/Roboto/

    - assets/icons/App_Icon/
    - assets/icons/Splash/
    - assets/icons/OnBoarding/
    - assets/icons/New_Password/
    - assets/icons/Login/
    - assets/icons/Search/
    - assets/icons/Home/
    - assets/icons/Notifications/
    - assets/icons/Products/

    - assets/imgs/Home/
    - assets/imgs/Notifications/

    - assets/jsons/
