// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';

import 'features/03_home/domain/entity/fruit_entity.dart';
import 'features/03_home/domain/entity/fruit_sub_entity.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(FruitsEntityAdapter());
    registerAdapter(HealthInfoEntityAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(FruitsEntityAdapter());
    registerAdapter(HealthInfoEntityAdapter());
  }
}
